-- =================================================================
-- BISMA APP DATABASE SCHEMA (SUPABASE / POSTGRESQL)
-- =================================================================
-- Copy and paste this entire script into the Supabase SQL Editor.
-- This script handles: Table Creation, Relationships, Indexes, RLS, and Seed Data.

-- 1. CLEANUP (Reset Schema if exists)
DROP TABLE IF EXISTS attendance_logs CASCADE;
DROP TABLE IF EXISTS journals CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS trash_transactions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;

-- 2. TABLE DEFINITIONS

-- Table: App Config (Global Settings)
CREATE TABLE app_config (
    id bigint generated by default as identity primary key,
    app_name text DEFAULT 'BISMA APP',
    school_name text DEFAULT 'SDN BAUJENG 1',
    logo_url_1x1 text,
    logo_url_3x4 text,
    logo_url_4x3 text,
    letterhead_url text,
    announcement_color text DEFAULT 'yellow',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Teachers (Guru)
CREATE TABLE teachers (
    id bigint generated by default as identity primary key,
    nip text UNIQUE NOT NULL,
    name text NOT NULL,
    jenis_kelamin text DEFAULT 'P', -- 'L' atau 'P'
    subject text, -- Mapel yang diampu
    jenis_guru text DEFAULT 'Guru Mapel', -- 'Guru Kelas' atau 'Guru Mapel'
    wali_kelas text DEFAULT '-',
    status text DEFAULT 'Active',
    password text DEFAULT 'guru', -- Stored as plain text per app logic
    target_jp int DEFAULT 24,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Students (Siswa)
CREATE TABLE students (
    id bigint generated by default as identity primary key,
    nisn text UNIQUE NOT NULL,
    nis text, -- Nomor Induk Siswa (Lokal)
    name text NOT NULL,
    tempat_lahir text,
    tanggal_lahir date,
    nama_ayah text,
    nama_ibu text,
    class_name text NOT NULL,
    status text DEFAULT 'Active',
    password text DEFAULT 'siswa', -- Stored as plain text per app logic
    points int DEFAULT 0,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Schedules (Jadwal KBM)
CREATE TABLE schedules (
    id bigint generated by default as identity primary key,
    day text NOT NULL, -- Senin, Selasa, etc.
    time text NOT NULL, -- e.g. "Jam Ke-1"
    class_name text NOT NULL,
    subject text NOT NULL,
    teacher_name text NOT NULL,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Grades (Nilai)
CREATE TABLE grades (
    id bigint generated by default as identity primary key,
    student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    student_name text, -- Denormalized for easier CSV export
    class_name text,
    subject text NOT NULL,
    ph int DEFAULT 0,
    pts int DEFAULT 0,
    pas int DEFAULT 0,
    created_at timestamptz DEFAULT timezone('utc'::text, now()),
    UNIQUE(student_id, subject) -- Critical for Upsert logic in TeacherDashboard
);

-- Table: Journals (Jurnal Harian)
CREATE TABLE journals (
    id bigint generated by default as identity primary key,
    teacher_id text NOT NULL, -- Flexible ID (can be Auth UUID or Teacher Table ID)
    class_name text NOT NULL,
    material jsonb, -- Stores the array of materials [{mapel, jam, materi}]
    notes text,
    cleanliness_status text,
    validation_status text DEFAULT 'Verified',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Attendance Logs (Absensi Detail per Jurnal)
CREATE TABLE attendance_logs (
    id bigint generated by default as identity primary key,
    journal_id bigint NOT NULL REFERENCES journals(id) ON DELETE CASCADE,
    student_name text,
    status text CHECK (status IN ('S', 'I', 'A', 'D')),
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Trash Transactions (Bank Sampah)
CREATE TABLE trash_transactions (
    id bigint generated by default as identity primary key,
    student_id bigint REFERENCES students(id) ON DELETE SET NULL,
    student_name text,
    type text, -- Plastik, Kertas, etc.
    weight numeric(10, 2) DEFAULT 0.00,
    amount numeric(15, 2) DEFAULT 0.00,
    status text DEFAULT 'Deposit', -- Deposit vs Withdraw
    date date DEFAULT CURRENT_DATE,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Tasks (Tugas)
CREATE TABLE tasks (
    id bigint generated by default as identity primary key,
    teacher_name text,
    class_name text,
    subject text,
    title text,
    description text,
    deadline text,
    link text,
    status text DEFAULT 'New',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- 3. ROW LEVEL SECURITY (RLS)
-- We enable RLS but create "OPEN" policies so your app works immediately 
-- without needing complex auth setup on the Supabase side for now.

ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE trash_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Helper function to open up a table
CREATE OR REPLACE FUNCTION enable_open_access(tbl text) RETURNS void AS $$
BEGIN
    EXECUTE format('CREATE POLICY "Public Read" ON %I FOR SELECT USING (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Insert" ON %I FOR INSERT WITH CHECK (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Update" ON %I FOR UPDATE USING (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Delete" ON %I FOR DELETE USING (true)', tbl);
END;
$$ LANGUAGE plpgsql;

-- Apply open access to all tables
SELECT enable_open_access('app_config');
SELECT enable_open_access('teachers');
SELECT enable_open_access('students');
SELECT enable_open_access('schedules');
SELECT enable_open_access('grades');
SELECT enable_open_access('journals');
SELECT enable_open_access('attendance_logs');
SELECT enable_open_access('trash_transactions');
SELECT enable_open_access('tasks');

-- 4. SEED DATA (Data Awal untuk Demo)

-- Students
INSERT INTO students (nisn, nis, name, class_name, password, tempat_lahir, tanggal_lahir, nama_ayah, nama_ibu) VALUES 
('304910293', '1001', 'Ahmad Dahlan', '5A', 'siswa', 'Pasuruan', '2015-05-12', 'Suparman', 'Suminah'),
('304910294', '1002', 'Budi Santoso', '5A', 'siswa', 'Malang', '2015-08-20', 'Joko', 'Sri'),
('304910295', '1003', 'Citra Kirana', '5A', 'siswa', 'Surabaya', '2015-12-01', 'Bambang', 'Wati'),
('1001', '1004', 'Dewi Sartika', '5A', 'siswa', 'Pasuruan', '2015-01-15', 'Agus', 'Lina');

-- Teachers
INSERT INTO teachers (nip, name, jenis_kelamin, subject, jenis_guru, wali_kelas, password) VALUES 
('19800101', 'Hj. Siti Aminah', 'P', 'Guru Kelas', 'Guru Kelas', '5A', 'guru'),
('19750202', 'Drs. Supriyanto', 'L', 'PJOK', 'Guru Mapel', '-', 'guru'),
('19900303', 'Rina Wati, S.Pd', 'P', 'Bahasa Inggris', 'Guru Mapel', '-', 'guru');

-- Schedules
INSERT INTO schedules (day, time, class_name, subject, teacher_name) VALUES
('Senin', 'Jam Ke-1', '5A', 'Matematika', 'Hj. Siti Aminah'),
('Senin', 'Jam Ke-2', '5A', 'Matematika', 'Hj. Siti Aminah'),
('Senin', 'Jam Ke-3', '5A', 'PJOK', 'Drs. Supriyanto'),
('Selasa', 'Jam Ke-1', '5A', 'Bahasa Indonesia', 'Hj. Siti Aminah');

-- Grades
INSERT INTO grades (student_id, student_name, class_name, subject, ph, pts, pas) 
SELECT id, name, class_name, 'Matematika', 85, 88, 90 FROM students WHERE class_name = '5A';
