-- =================================================================
-- BISMA APP DATABASE SCHEMA (SUPABASE / POSTGRESQL)
-- =================================================================

-- 1. CLEANUP (Reset Schema if exists)
DROP TABLE IF EXISTS staff_logs CASCADE;
DROP TABLE IF EXISTS attendance_logs CASCADE;
DROP TABLE IF EXISTS journals CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS trash_transactions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;

-- 2. TABLE DEFINITIONS

-- Table: App Config (Global Settings)
CREATE TABLE app_config (
    id bigint generated by default as identity primary key,
    app_name text DEFAULT 'BISMA APP',
    school_name text DEFAULT 'SDN BAUJENG I BEJI',
    principal_name text DEFAULT 'AKHMAD NASOR, S.Pd',
    principal_nip text DEFAULT '198704082019031001',
    logo_url_1x1 text,
    logo_url_3x4 text,
    logo_url_4x3 text,
    letterhead_url text,
    announcement_title text,
    announcement_type text,
    announcement_date text,
    announcement_time text,
    announcement_desc text,
    announcement_color text DEFAULT 'yellow',
    ph_count int DEFAULT 2,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Teachers & Staff (Guru & Tendik)
CREATE TABLE teachers (
    id bigint generated by default as identity primary key,
    nip text UNIQUE NOT NULL,
    name text NOT NULL,
    jenis_kelamin text DEFAULT 'P',
    subject text,
    jenis_guru text DEFAULT 'Guru Mapel', -- Options: Guru Kelas, Guru Mapel, Kepala Sekolah, Staff
    wali_kelas text DEFAULT '-',
    status text DEFAULT 'Active',
    password text DEFAULT 'guru',
    target_jp int DEFAULT 24,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Students (Siswa)
CREATE TABLE students (
    id bigint generated by default as identity primary key,
    nisn text NOT NULL, 
    nis text,
    name text NOT NULL,
    tempat_lahir text,
    tanggal_lahir date,
    nama_ayah text,
    nama_ibu text,
    class_name text NOT NULL,
    status text DEFAULT 'Active',
    password text DEFAULT 'siswa',
    points int DEFAULT 0,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Schedules (Jadwal KBM)
CREATE TABLE schedules (
    id bigint generated by default as identity primary key,
    day text NOT NULL,
    time text NOT NULL,
    class_name text NOT NULL,
    subject text NOT NULL,
    teacher_name text NOT NULL,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Grades (Nilai)
CREATE TABLE grades (
    id bigint generated by default as identity primary key,
    student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    student_name text,
    class_name text,
    subject text NOT NULL,
    ph_scores jsonb DEFAULT '[]', 
    pts int DEFAULT 0,
    pas int DEFAULT 0,
    created_at timestamptz DEFAULT timezone('utc'::text, now()),
    UNIQUE(student_id, subject)
);

-- Table: Journals (Jurnal Harian Guru)
CREATE TABLE journals (
    id bigint generated by default as identity primary key,
    teacher_id text NOT NULL,
    class_name text NOT NULL,
    material jsonb,
    notes text,
    cleanliness_status text,
    validation_status text DEFAULT 'Verified',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Staff Logs (Jurnal Harian Tendik/KS)
CREATE TABLE staff_logs (
    id bigint generated by default as identity primary key,
    staff_name text NOT NULL,
    staff_role text NOT NULL, -- Kepala Sekolah / Staff
    activity_type text NOT NULL, -- e.g., Supervisi, Rapat, Administrasi
    description text,
    location text, -- Kantor, Dinas, dll
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Attendance Logs (Absensi Detail per Jurnal)
CREATE TABLE attendance_logs (
    id bigint generated by default as identity primary key,
    journal_id bigint NOT NULL REFERENCES journals(id) ON DELETE CASCADE,
    student_name text,
    status text CHECK (status IN ('S', 'I', 'A', 'D')),
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Trash Transactions (Bank Sampah)
CREATE TABLE trash_transactions (
    id bigint generated by default as identity primary key,
    student_id bigint REFERENCES students(id) ON DELETE SET NULL,
    student_name text,
    type text,
    weight numeric(10, 2) DEFAULT 0.00,
    amount numeric(15, 2) DEFAULT 0.00,
    status text DEFAULT 'Deposit',
    date date DEFAULT CURRENT_DATE,
    description text,
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Tasks (Tugas)
CREATE TABLE tasks (
    id bigint generated by default as identity primary key,
    teacher_name text,
    class_name text,
    subject text,
    title text,
    description text,
    deadline text,
    link text,
    status text DEFAULT 'New',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Permissions (Izin/Sakit)
CREATE TABLE permissions (
    id bigint generated by default as identity primary key,
    student_name text,
    class_name text,
    type text,
    date date,
    reason text,
    status text DEFAULT 'Pending',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Table: Good Deeds (Anak Hebat)
CREATE TABLE good_deeds (
    id bigint generated by default as identity primary key,
    student_name text,
    class_name text,
    activity text,
    date date,
    time text,
    status text DEFAULT 'Pending',
    created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- 3. ROW LEVEL SECURITY (RLS)
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE trash_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE good_deeds ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION enable_open_access(tbl text) RETURNS void AS $$
BEGIN
    EXECUTE format('CREATE POLICY "Public Read" ON %I FOR SELECT USING (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Insert" ON %I FOR INSERT WITH CHECK (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Update" ON %I FOR UPDATE USING (true)', tbl);
    EXECUTE format('CREATE POLICY "Public Delete" ON %I FOR DELETE USING (true)', tbl);
END;
$$ LANGUAGE plpgsql;

SELECT enable_open_access('app_config');
SELECT enable_open_access('teachers');
SELECT enable_open_access('students');
SELECT enable_open_access('schedules');
SELECT enable_open_access('grades');
SELECT enable_open_access('journals');
SELECT enable_open_access('staff_logs');
SELECT enable_open_access('attendance_logs');
SELECT enable_open_access('trash_transactions');
SELECT enable_open_access('tasks');
SELECT enable_open_access('permissions');
SELECT enable_open_access('good_deeds');

-- 4. SEED DATA 
-- NOTE: ALL DUMMY STUDENTS AND TEACHERS HAVE BEEN REMOVED.
-- PLEASE USE THE ADMIN DASHBOARD TO IMPORT REAL DATA.

-- App Config (Identity)
INSERT INTO app_config (school_name, principal_name, principal_nip) 
VALUES ('SDN BAUJENG I BEJI', 'AKHMAD NASOR, S.Pd', '198704082019031001');
